package com.example.flavi.gigsuite.DAO.DAOExterno;

/**
 * Created by junior on 25/05/17.
 */

public class PerfilDAOExterno {

    //TODO: FAZER INSERT QUE CADASTRA O PRIMEIRO PERFIL BASEADO NO USUARIO
    //TODO: FAZER UPDATE - METODO QUE VAI SER SEMPRE UTILIZADO
    //TODO: FAZER SELECT - METODO QUE SERÃO UTILIZADOS NOS FILTROS

}
