package com.example.flavi.gigsuite.DAO;

/**
 * Created by junior on 26/05/17.
 */

public class UtilDAO {

    //TODO: ESSA CLASSE TERA OS DAOS QUE SERAO UTEIS PARA O USUARIO

    //TODO: IMPLEMENTAR INSERT
    //TODO: IMPLEMENTAR SELECT
    //TODO: IMPLEMENTAR DELETE

    /*
    * EXEMPLO DE UTILIZAÇÃO DESSA CLASSE
    *
    * HISTÓRICO DE PESQUISAS DO USUARIO
    * ENTRE OUTRAS COISAS QUE SERÃO PARTICULARES DELE
    * */

}
